Add more SGX tasks
faasm/experiment-sgx pull request #8
Opened 2021-10-04 16:19 UTC by csegarragonz

2021-10-05 10:44 UTC, csegarragonz commented on tasks/sgx.py
> +def configure(ctx):
This file was comitted before, feel free to leave comments on any line, even if it is not part of this `diff`.

2021-10-07 14:27 UTC, Shillaker requested changes
Just a few smaller things. Looks pretty gnarly 😬

2021-10-07 14:27 UTC, Shillaker commented on tasks/sgx.py
> +    """
This is convenient but looks like it's ubuntu 18.04-specific, might be worth putting a warning in the `README` about OS and version dependencies, then including a link to the official instructions for anyone who wants to diverge from that.

2021-10-07 14:27 UTC, Shillaker commented on README.md
> +
I know we don't really enforce style on `.md` files but in the rest of the repos we put a linebreak before and after code snippets. Doesn't change the presentation of the rendered markdown but it makes the source easier to read.

2021-10-07 14:27 UTC, Shillaker commented on tasks/sgx.py
>          "cd /opt/maa/intel.sdk.attest.sample/genquotes && AZDCAP_DEBUG_LOG_LEVEL=INFO bash ./runall.sh",
Rather than doing `cd &&` in these commands you can specify a working directory with the `cwd` kwarg.

2021-10-15 09:57 UTC, Shillaker approved these changes

2021-10-15 10:30 UTC, merged